from graph import Graph


# Create a more complex example graph - a city network
def create_city_network():
    g = Graph()

    # Add vertices (cities)
    new_york = g.add_vertex("New York")
    los_angeles = g.add_vertex("Los Angeles")
    chicago = g.add_vertex("Chicago")
    houston = g.add_vertex("Houston")
    phoenix = g.add_vertex("Phoenix")
    philadelphia = g.add_vertex("Philadelphia")
    san_antonio = g.add_vertex("San Antonio")
    san_diego = g.add_vertex("San Diego")
    dallas = g.add_vertex("Dallas")
    san_jose = g.add_vertex("San Jose")
    austin = g.add_vertex("Austin")
    jacksonville = g.add_vertex("Jacksonville")
    fort_worth = g.add_vertex("Fort Worth")
    columbus = g.add_vertex("Columbus")
    seattle = g.add_vertex("Seattle")
    denver = g.add_vertex("Denver")
    boston = g.add_vertex("Boston")
    portland = g.add_vertex("Portland")
    las_vegas = g.add_vertex("Las Vegas")
    miami = g.add_vertex("Miami")

    # Add edges (connections between cities) with distance in miles
    g.add_edge(new_york, boston, 215)
    g.add_edge(new_york, philadelphia, 95)
    g.add_edge(los_angeles, san_diego, 120)
    g.add_edge(los_angeles, las_vegas, 270)
    g.add_edge(los_angeles, san_jose, 340)
    g.add_edge(chicago, columbus, 350)
    g.add_edge(chicago, denver, 1000)
    g.add_edge(houston, dallas, 240)
    g.add_edge(houston, san_antonio, 200)
    g.add_edge(houston, austin, 165)
    g.add_edge(phoenix, las_vegas, 300)
    g.add_edge(phoenix, san_diego, 355)
    g.add_edge(philadelphia, boston, 305)
    g.add_edge(san_antonio, austin, 80)
    g.add_edge(san_antonio, dallas, 275)
    g.add_edge(san_diego, las_vegas, 330)
    g.add_edge(dallas, fort_worth, 35)
    g.add_edge(dallas, austin, 195)
    g.add_edge(san_jose, san_diego, 460)
    g.add_edge(san_jose, portland, 635)
    g.add_edge(san_jose, seattle, 835)
    g.add_edge(austin, fort_worth, 190)
    g.add_edge(jacksonville, miami, 345)
    g.add_edge(columbus, philadelphia, 475)
    g.add_edge(seattle, portland, 175)
    g.add_edge(seattle, denver, 1300)
    g.add_edge(denver, las_vegas, 750)
    g.add_edge(denver, phoenix, 850)
    g.add_edge(miami, jacksonville, 345)
    g.add_edge(las_vegas, denver, 750)

    return g, new_york
